// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitioWebPwa.Models;

#nullable disable

namespace SitioWebPwa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SitioWebPwa.Models.Producto", b =>
                {
                    b.Property<int>("CodigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProducto"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("CodigoProducto");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            CodigoProducto = 1,
                            Cantidad = 0,
                            Detalle = "Camiseta titular de juego unisex",
                            Imagen = "/img/CamisetaTitularDeca.png",
                            NombreProducto = "Camiseta Titular",
                            Precio = 50000.0
                        },
                        new
                        {
                            CodigoProducto = 2,
                            Cantidad = 0,
                            Detalle = "Camiseta Suplente de juego unisex",
                            Imagen = "/img/CamisetaSuplenteDeca.png",
                            NombreProducto = "Camiseta Suplente",
                            Precio = 50000.0
                        },
                        new
                        {
                            CodigoProducto = 3,
                            Cantidad = 0,
                            Detalle = "Short titular de juego unisex",
                            Imagen = "/img/ShortTitularDeca.png",
                            NombreProducto = "Short Titular",
                            Precio = 25000.0
                        },
                        new
                        {
                            CodigoProducto = 4,
                            Cantidad = 0,
                            Detalle = "Short suplente Camiseta titular de juego unisex",
                            Imagen = "/img/ShortSuplenteDeca.png",
                            NombreProducto = "Short Suplente",
                            Precio = 25000.0
                        },
                        new
                        {
                            CodigoProducto = 5,
                            Cantidad = 0,
                            Detalle = "Termo y Mate del violeta",
                            Imagen = "/img/KitMateroDeca.png",
                            NombreProducto = "Kit Matero",
                            Precio = 65000.0
                        },
                        new
                        {
                            CodigoProducto = 6,
                            Cantidad = 0,
                            Detalle = "Buzo DCVD",
                            Imagen = "/img/BuzoDeca.png",
                            NombreProducto = "Buzo Decaño",
                            Precio = 80000.0
                        },
                        new
                        {
                            CodigoProducto = 7,
                            Cantidad = 0,
                            Detalle = "Piluso Vamos Violeta",
                            Imagen = "/img/PilusoDeca.png",
                            NombreProducto = "Piluso",
                            Precio = 20000.0
                        },
                        new
                        {
                            CodigoProducto = 8,
                            Cantidad = 0,
                            Detalle = "Medias de futbol DCVD",
                            Imagen = "/img/MediasDeca.png",
                            NombreProducto = "Medias de futbol",
                            Precio = 10000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
